[egg_info]
tag_build = 
tag_date = 0

[metadata]
license_files = README.md, CHANGELOG.md

[options]
install_requires =
    csvpack==0.1.0.dev4
    base_dumper==0.2.0.dev4
    pgpack==0.3.3.dev5
    psycopg_binary>=3.3.3
    psycopg>=3.3.3
    light-compressor==0.1.1.dev1

[options.package_data]
* =
    common/queries/*.sql, common/*.pyx, common/*.pyi, common/*.pxd
